### ISSUE TITLE
Using &nbsp; is not the best way for indenting the table

### ISSUE THREAD

**Issue by eljulians** [julenpardo/tinymce-table-of-contents#2]
The leading spaces remain "clickable":

![indenting with spaces](https://cloud.githubusercontent.com/assets/12843626/17084923/e442cb4a-51ca-11e6-98c0-43a60722b993.png)

Consider using description lists (`dl`) instead.

**Reopened 25-07-2016**: could it be as simple as placing the `&nbsp;` entities out of the anchor? E.g.: `&nbsp;&nbsp;&nbsp;&nbsp;<a href="#">1.1. blablabla</a>`

**Comment by julenpardo** [comment]
`generateIndentation` docblock has to be updated before closing this issue.

**Comment by julenpardo** [comment]
`generateIndentation()`  docblock has to be updated before closing this issue.

**Comment by julenpardo** [comment]
Fixed and merged to dev, see commit 2aca61c.

**Comment by julenpardo** [comment]
**Reopened 25-07-2016**: could it be as simple as placing the `&nbsp;` entities out of the anchor? E.g.: `&nbsp;&nbsp;&nbsp;&nbsp;<a href="#">1.1. blablabla</a>`

**Comment by julenpardo** [comment]
Fixed and merged to dev, see commit 28ea7e2.
